### ISSUE TITLE
"Unknown" Folder

### ISSUE THREAD

**Issue by KimyHardy** [jerickson314/sdscanner#2]
when I create a new folder, or this is created by another app, if i use Sd Scanner when i connect my device to the pc, the folder is corrupted, it doesn't seem a folder, it seems like a file with no extension and i have to delete it.

BTW, i like your app :}

**Comment by jerickson314** [comment]
Closing this bug, because SD Scanner 1.11 will now refuse to scan an empty folder. It's not an ideal solution, but it will prevent the permanent corruption problem seen here, and I don't think an empty folder has any value in the media database beyond showing up in MTP.
