### ISSUE TITLE
SDScanner has been moved to F-Droid archive

### ISSUE THREAD

**Issue by tomikmar** [jerickson314/sdscanner#21]
SDScanner  has been moved to F-Droid archive. It  should be enough to introduce a small change (e.g. merge translation pull request) and update the manifest to move it back to the main repository.

**Comment by tomikmar** [comment]
I can help with this if you gave me rights to the project.

**Comment by jerickson314** [comment]
Thanks for letting me know, and sorry I've been MIA. I just merged the pull requests and invited you as a collaborator.

Would you be interested in doing more to maintain SDScanner? No pressure, but as you can see, I haven't had much time or energy to put into it for quite some time now. I can push stuff to the Play Store once I get my build setup back up. (Probably I'll have a chance to do that tonight and do a release with the changes from the pull requests.) Of course, I'll credit you if you do so.

**Comment by tomikmar** [comment]
Thank you. I am not sure if I have enough time to maintain SDScanner, but it is a useful and complete app and it is definitely worth keeping it alive, so I can help with small things. From my point of view it is especially important to have it in F-Droid main repository which is my preferred source of software.

**Comment by tomikmar** [comment]
I updated version to [1.12](https://github.com/jerickson314/sdscanner/commit/db31205aeec23d707549d4405bbe081a56ac552a) to let F-Droid detect changes.

**Comment by tomikmar** [comment]
F-Droid found changes, but build wasn't triggered, so I created new issue:
* https://gitlab.com/fdroid/fdroiddata/issues/850

**Comment by ildar** [comment]
I see.
@tomikmar , as you have access to the repo, please consider using git tags.
It is far more reliable and observable way to mark important commits. And
it's the most preferable way for F-Droid robots too.
As the next step you could also Release.

**Comment by tomikmar** [comment]
I agree. I'll create tag. What do you think about this tag format: http://semver.org/ , e.g. in our case 1.12.0 ?

**Comment by ildar** [comment]
Tags are good whichever naming conversion you take. Looks good to me. 👍

**Comment by tomikmar** [comment]
Tag created: [1.12.0](https://github.com/jerickson314/sdscanner/tree/1.12.0)

**Comment by tomikmar** [comment]
Good news. The new version of SDScanner (1.12.0) is available in F-Droid main repository:
* https://f-droid.org/packages/com.gmail.jerickson314.sdscanner/

I cannot release to Google Play because I don't have rights/keys.

Since this issue was about F-Droid, I think we can close it.
